from typing import Optional

from serial import Serial

class ConsolePosix:
    infd: int

    def __init__(self) -> None: ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def waitchar(self, pyb_serial: Serial) -> None: ...
    def readchar(self) -> Optional[bytes]: ...
    def write(self, buf: bytes) -> None: ...

class ConsoleWindows:
    def __init__(self) -> None: ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def inWaiting(self) -> int: ...
    def waitchar(self, pyb_serial: Serial) -> None: ...
    def readchar(self) -> Optional[bytes]: ...
    def write(self, buf: bytes) -> None: ...
