from typing import Optional

from .transport import Transport

class State:
    transport: Transport

    def __init__(self) -> None: ...
    def did_action(self) -> bool: ...
    def run_repl_on_completion(self) -> bool: ...
    def ensure_connected(self) -> None: ...
    def ensure_raw_repl(self, soft_reset: Optional[bool] = None) -> None: ...
    def ensure_friendly_repl(self) -> None: ...

def main() -> int: ...
